[functions]
    directory="functions"

[[redirects]]
    from = "/*"
    to = "/.netlify/functions/routes/moviesRoutes"

[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"